global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using OpenAI;
global using System.Text.Json;
global using System.Collections.Immutable;
global using Common.AiDevsApi.Contracts;
global using Common.AiDevsApi.Models;
global using System.ComponentModel.DataAnnotations;
